# Generated by Django 2.1.12 on 2020-06-12 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20200609_0318'),
        ('partners', '0003_auto_20200609_0318'),
        ('datacom', '0003_auto_20200609_0318'),
        ('commons2', '0002_auto_20200611_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='datacom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacom.Datacom'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Partner'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='close_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='open_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
