# Generated by Django 3.0.7 on 2020-06-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons2', '0004_auto_20200612_1714'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('name', 'datacom'), name='datacom_holiday'),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('name', 'partner'), name='partner_holiday'),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('name', 'company'), name='company_holiday'),
        ),
    ]
