# Generated by Django 3.0.7 on 2020-06-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons2', '0005_auto_20200612_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='close_time2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='open_time2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
