# Generated by Django 3.0.7 on 2020-06-16 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20200609_0318'),
        ('companies', '0003_auto_20200609_0318'),
        ('datacom', '0004_auto_20200612_1714'),
        ('commons2', '0006_auto_20200612_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('auto_approve_timecards', models.BooleanField(blank=True, default=False, null=True)),
                ('created_payroll_cycles', models.BooleanField(blank=True, default=False, null=True)),
                ('setup_attendance_rules', models.BooleanField(blank=True, default=False, null=True)),
                ('created_departments', models.BooleanField(blank=True, default=False, null=True)),
                ('created_employees', models.BooleanField(blank=True, default=False, null=True)),
                ('created_products', models.BooleanField(blank=True, default=False, null=True)),
                ('created_groups', models.BooleanField(blank=True, default=False, null=True)),
                ('assigned_module_managers', models.BooleanField(blank=True, default=False, null=True)),
                ('charge_sales_tax', models.BooleanField(blank=True, default=False, null=True)),
                ('created_sales_tax', models.BooleanField(blank=True, default=False, null=True)),
                ('enable_pto', models.BooleanField(blank=True, default=False, null=True)),
                ('enable_benefits_tracking', models.BooleanField(blank=True, default=False, null=True)),
                ('enable_inventory_tracking', models.BooleanField(blank=True, default=False, null=True)),
                ('sick_days_year', models.IntegerField(blank=True, default=0, null=True)),
                ('personal_days_year', models.IntegerField(blank=True, default=0, null=True)),
                ('vacation_days_year', models.IntegerField(blank=True, default=0, null=True)),
                ('pto_days_year', models.IntegerField(blank=True, default=0, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('datacom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacom.Datacom')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Partner')),
            ],
        ),
    ]
