# Generated by Django 3.0.7 on 2020-06-17 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons2', '0007_generalsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='date_input',
        ),
        migrations.RemoveField(
            model_name='department',
            name='date_test',
        ),
        migrations.RemoveField(
            model_name='department',
            name='datetime_input',
        ),
    ]
