# Generated by Django 3.0.7 on 2020-06-19 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons2', '0008_auto_20200617_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='is_open',
            new_name='is_active',
        ),
    ]
