# Generated by Django 3.0.7 on 2020-06-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons2', '0010_auto_20200621_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='name',
            new_name='category',
        ),
        migrations.AddField(
            model_name='notification',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
