# Generated by Django 3.0.7 on 2020-06-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons2', '0011_auto_20200621_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='archived',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_declined',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
