# Generated by Django 3.0.7 on 2020-06-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons2', '0012_auto_20200623_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
