# Generated by Django 3.0.7 on 2020-06-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons2', '0013_auto_20200623_0523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date_sent',
            new_name='date_added',
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
