# Generated by Django 3.0.7 on 2020-06-25 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons2', '0015_auto_20200624_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='personal_days_year',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='pto_days_year',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='sick_days_year',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='vacation_days_year',
        ),
    ]
