# Generated by Django 3.0.7 on 2020-06-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons2', '0016_auto_20200625_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.RemoveConstraint(
            model_name='holiday',
            name='datacom_holiday',
        ),
        migrations.RemoveConstraint(
            model_name='holiday',
            name='partner_holiday',
        ),
        migrations.RemoveConstraint(
            model_name='holiday',
            name='company_holiday',
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('name', 'datacom', 'partner', 'company'), name='unique_holidays'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
