# Generated by Django 3.0.7 on 2020-07-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons2', '0017_auto_20200625_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
