# Generated by Django 3.0.7 on 2020-07-19 02:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vthpp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='billing_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='card_number',
            field=models.CharField(default=231231, max_length=18, validators=[django.core.validators.RegexValidator('^\\d{1,18}$')]),
            preserve_default=False,
        ),
    ]
