# Generated by Django 3.0.7 on 2020-07-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vthpp', '0002_auto_20200719_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
