# Generated by Django 3.0.7 on 2020-06-25 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datacom', '0004_auto_20200612_1714'),
        ('companies', '0003_auto_20200609_0318'),
        ('partners', '0003_auto_20200609_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added_handbook', models.DateTimeField(auto_now_add=True)),
                ('employee_handbook', models.FileField(upload_to='employees/documents/handbooks')),
                ('date_added_policy_procedures', models.DateTimeField(auto_now_add=True)),
                ('employee_policy_procedures', models.FileField(upload_to='employees/documents/handbooks')),
                ('date_added_code_of_conduct', models.DateTimeField(auto_now_add=True)),
                ('employee_code_of_conduct', models.FileField(upload_to='employees/documents/handbooks')),
                ('date_added_employment_agmt', models.DateTimeField(auto_now_add=True)),
                ('employee_employment_agmt', models.FileField(upload_to='employees/documents/handbooks')),
                ('date_added_compensation', models.DateTimeField(auto_now_add=True)),
                ('employee_compensation', models.FileField(upload_to='employees/documents/handbooks')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacom.Datacom')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added_handbook', models.DateTimeField(auto_now_add=True)),
                ('company_handbook', models.FileField(upload_to='documents/handbooks')),
                ('date_added_policy_procedures', models.DateTimeField(auto_now_add=True)),
                ('company_policy_procedures', models.FileField(upload_to='documents/handbooks')),
                ('date_added_code_of_conduct', models.DateTimeField(auto_now_add=True)),
                ('company_code_of_conduct', models.FileField(upload_to='documents/handbooks')),
                ('date_added_employment_agmt', models.DateTimeField(auto_now_add=True)),
                ('company_employment_agmt', models.FileField(upload_to='documents/handbooks')),
                ('date_added_compensation', models.DateTimeField(auto_now_add=True)),
                ('company_compensation', models.FileField(upload_to='documents/handbooks')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('datacom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacom.Datacom')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('sick_days_year', models.IntegerField(blank=True, default=0, null=True)),
                ('personal_days_year', models.IntegerField(blank=True, default=0, null=True)),
                ('vacation_days_year', models.IntegerField(blank=True, default=0, null=True)),
                ('pto_days_year', models.IntegerField(blank=True, default=0, null=True)),
                ('has_medical', models.BooleanField(blank=True, default=False, null=True)),
                ('medical_insurance_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('has_dental', models.BooleanField(blank=True, default=False, null=True)),
                ('dental_insurance_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('has_ADnD', models.BooleanField(blank=True, default=False, null=True)),
                ('ADnD_insurance_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('has_vision', models.BooleanField(blank=True, default=False, null=True)),
                ('vision_insurance_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('has_401k', models.BooleanField(blank=True, default=False, null=True)),
                ('financial_401k_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacom.Datacom')),
            ],
        ),
    ]
