# Generated by Django 3.0.7 on 2021-02-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('sick_days_year', models.IntegerField(blank=True, default=0, null=True)),
                ('sick_days_remaining', models.IntegerField(blank=True, null=True)),
                ('personal_days_year', models.IntegerField(blank=True, default=0, null=True)),
                ('personal_days_remaining', models.IntegerField(blank=True, null=True)),
                ('vacation_days_year', models.IntegerField(blank=True, default=0, null=True)),
                ('vacation_days_remaining', models.IntegerField(blank=True, null=True)),
                ('pto_days_year', models.IntegerField(blank=True, default=0, null=True)),
                ('pto_days_remaining', models.IntegerField(blank=True, null=True)),
                ('has_medical', models.BooleanField(blank=True, default=False, null=True)),
                ('medical_insurance_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('has_dental', models.BooleanField(blank=True, default=False, null=True)),
                ('dental_insurance_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('has_ADnD', models.BooleanField(blank=True, default=False, null=True)),
                ('ADnD_insurance_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('has_vision', models.BooleanField(blank=True, default=False, null=True)),
                ('vision_insurance_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('has_401k', models.BooleanField(blank=True, default=False, null=True)),
                ('contribution_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('financial_401k_provider', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added_handbook', models.DateTimeField(auto_now_add=True)),
                ('company_handbook', models.FileField(blank=True, null=True, upload_to='documents/handbooks')),
                ('date_added_policy_procedures', models.DateTimeField(auto_now_add=True)),
                ('company_policy_procedures', models.FileField(blank=True, null=True, upload_to='documents/handbooks')),
                ('date_added_code_of_conduct', models.DateTimeField(auto_now_add=True)),
                ('company_code_of_conduct', models.FileField(blank=True, null=True, upload_to='documents/handbooks')),
                ('date_added_employment_agmt', models.DateTimeField(auto_now_add=True)),
                ('company_employment_agmt', models.FileField(blank=True, null=True, upload_to='documents/handbooks')),
                ('date_added_compensation', models.DateTimeField(auto_now_add=True)),
                ('company_compensation', models.FileField(blank=True, null=True, upload_to='documents/handbooks')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added_handbook', models.DateTimeField(auto_now_add=True)),
                ('employee_handbook', models.FileField(blank=True, null=True, upload_to='employees/documents/handbooks')),
                ('signed_handbook', models.BooleanField(blank=True, default=False, null=True)),
                ('date_added_policy_procedures', models.DateTimeField(auto_now_add=True)),
                ('employee_policy_procedures', models.FileField(blank=True, null=True, upload_to='employees/documents/handbooks')),
                ('signed_policies_procedures', models.BooleanField(blank=True, default=False, null=True)),
                ('date_added_code_of_conduct', models.DateTimeField(auto_now_add=True)),
                ('employee_code_of_conduct', models.FileField(blank=True, null=True, upload_to='employees/documents/handbooks')),
                ('signed_code_of_conduct', models.BooleanField(blank=True, default=False, null=True)),
                ('date_added_employment_agmt', models.DateTimeField(auto_now_add=True)),
                ('employee_employment_agmt', models.FileField(blank=True, null=True, upload_to='employees/documents/handbooks')),
                ('signed_ee_agmt', models.BooleanField(blank=True, default=False, null=True)),
                ('date_added_compensation', models.DateTimeField(auto_now_add=True)),
                ('employee_compensation', models.FileField(blank=True, null=True, upload_to='employees/documents/handbooks')),
                ('signed_comp_plan', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MileageReimbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('miles_driven', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Declined', 'Declined'), ('Open', 'Open'), ('Expired', 'Expired'), ('Deleted', 'Deleted')], max_length=100, null=True)),
                ('disposition_date', models.DateTimeField(blank=True, null=True)),
                ('approval_remarks', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='employees/mileage-receipts')),
            ],
        ),
    ]
