# Generated by Django 3.0.7 on 2020-06-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefits',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='companydocuments',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companydocuments',
            name='datacom',
        ),
        migrations.RemoveField(
            model_name='companydocuments',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='employeedocuments',
            name='employee',
        ),
        migrations.AddField(
            model_name='benefits',
            name='contribution_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='benefits',
            name='personal_days_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='benefits',
            name='pto_days_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='benefits',
            name='sick_days_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='benefits',
            name='vacation_days_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocuments',
            name='signed_code_of_conduct',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='employeedocuments',
            name='signed_comp_plan',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='employeedocuments',
            name='signed_ee_agmt',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='employeedocuments',
            name='signed_handbook',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='employeedocuments',
            name='signed_policies_procedures',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
