# Generated by Django 3.0.7 on 2020-06-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresources', '0002_auto_20200625_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='MileageReimbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('miles_driven', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Declined', 'Declined'), ('Open', 'Open'), ('Expired', 'Expired'), ('Deleted', 'Deleted')], max_length=100, null=True)),
                ('disposition_date', models.DateTimeField(blank=True, null=True)),
                ('approval_remarks', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('read', models.BooleanField(blank=True, default=False, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='employees/mileage-receipts')),
            ],
        ),
        migrations.AlterField(
            model_name='companydocuments',
            name='company_code_of_conduct',
            field=models.FileField(blank=True, null=True, upload_to='documents/handbooks'),
        ),
        migrations.AlterField(
            model_name='companydocuments',
            name='company_compensation',
            field=models.FileField(blank=True, null=True, upload_to='documents/handbooks'),
        ),
        migrations.AlterField(
            model_name='companydocuments',
            name='company_employment_agmt',
            field=models.FileField(blank=True, null=True, upload_to='documents/handbooks'),
        ),
        migrations.AlterField(
            model_name='companydocuments',
            name='company_handbook',
            field=models.FileField(blank=True, null=True, upload_to='documents/handbooks'),
        ),
        migrations.AlterField(
            model_name='companydocuments',
            name='company_policy_procedures',
            field=models.FileField(blank=True, null=True, upload_to='documents/handbooks'),
        ),
        migrations.AlterField(
            model_name='employeedocuments',
            name='employee_code_of_conduct',
            field=models.FileField(blank=True, null=True, upload_to='employees/documents/handbooks'),
        ),
        migrations.AlterField(
            model_name='employeedocuments',
            name='employee_compensation',
            field=models.FileField(blank=True, null=True, upload_to='employees/documents/handbooks'),
        ),
        migrations.AlterField(
            model_name='employeedocuments',
            name='employee_employment_agmt',
            field=models.FileField(blank=True, null=True, upload_to='employees/documents/handbooks'),
        ),
        migrations.AlterField(
            model_name='employeedocuments',
            name='employee_handbook',
            field=models.FileField(blank=True, null=True, upload_to='employees/documents/handbooks'),
        ),
        migrations.AlterField(
            model_name='employeedocuments',
            name='employee_policy_procedures',
            field=models.FileField(blank=True, null=True, upload_to='employees/documents/handbooks'),
        ),
    ]
