# Generated by Django 3.0.7 on 2020-06-25 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanresources', '0004_remove_mileagereimbursement_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mileagereimbursement',
            name='date_added',
        ),
    ]
