# Generated by Django 3.0.7 on 2020-06-30 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200630_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mailing_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mailing_city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mailing_state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mailing_zip',
        ),
    ]
