# Generated by Django 3.0.7 on 2020-07-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacom', '0013_auto_20200721_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacom',
            name='dba_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='datacom',
            name='domain',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='datacom',
            name='legal_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
