# Generated by Django 2.1.12 on 2020-06-05 19:55

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('module_name', models.CharField(blank=True, max_length=250, null=True)),
                ('groupId', models.IntegerField(blank=True, null=True)),
                ('allDay', models.BooleanField(blank=True, default=False, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('daysOfWeek', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=7)),
                ('startTime', models.TimeField(blank=True, null=True)),
                ('endTime', models.TimeField(blank=True, null=True)),
                ('startRecur', models.DateField(blank=True, null=True)),
                ('endRecur', models.DateField(blank=True, null=True)),
                ('URL', models.CharField(blank=True, max_length=250, null=True)),
                ('classNames', models.CharField(blank=True, max_length=250, null=True)),
                ('editable', models.BooleanField(default=True)),
                ('startEditable', models.BooleanField(default=True)),
                ('durationEditable', models.BooleanField(default=True)),
                ('resourceEditable', models.BooleanField(default=True)),
                ('resourceId', models.CharField(blank=True, max_length=250, null=True)),
                ('resourceIds', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), blank=True, null=True, size=None)),
                ('overlap', models.BooleanField(default=True)),
                ('constraint', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('backgroundColor', models.CharField(blank=True, max_length=20, null=True)),
                ('textColor', models.CharField(blank=True, max_length=20, null=True)),
                ('borderColor', models.CharField(blank=True, max_length=20, null=True)),
                ('extendedProps', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('rrule', models.CharField(blank=True, max_length=250, null=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='attendees', to='employees.Employee')),
                ('contenttype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
            options={
                'ordering': ['start', 'title'],
            },
        ),
    ]
