# Generated by Django 3.0.7 on 2020-06-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200612_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybarcode',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='inventory/barcodes'),
        ),
    ]
