# Generated by Django 3.0.7 on 2020-07-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200628_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorybarcode',
            name='image',
        ),
        migrations.RemoveField(
            model_name='inventorybarcode',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='inventorybarcode',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='inventorybarcode',
            name='title',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sku',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='inventorybarcode',
            name='barcode_number',
            field=models.CharField(default='12345678', max_length=8),
            preserve_default=False,
        ),
    ]
