# Generated by Django 3.0.7 on 2020-07-29 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200729_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='is_variation',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='parent_item',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='tags',
        ),
    ]
