# Generated by Django 3.0.7 on 2020-07-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20200729_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='initial_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
