# Generated by Django 3.0.7 on 2020-07-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventory_initial_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='sale_expires',
            new_name='sale_expire_date',
        ),
        migrations.AddField(
            model_name='inventory',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='inventory/files'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='specifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorybarcode',
            name='is_sku',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorybarcode',
            name='is_upc',
            field=models.BooleanField(default=False),
        ),
    ]
