# Generated by Django 3.0.7 on 2021-02-12 20:13

from django.db import migrations, models
import django.db.models.deletion
import eventtools.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('datacom', '0001_initial'),
        ('employees', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(blank=True, choices=[('Vacation', 'Vacation'), ('Sick', 'Sick'), ('Personal', 'Personal'), ('Medical', 'Medical'), ('Paid Time Off', 'Paid Time Off')], max_length=50, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('days_requested', models.IntegerField(blank=True, default=1, null=True)),
                ('status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Declined', 'Declined'), ('Open', 'Open'), ('Expired', 'Expired'), ('Deleted', 'Deleted')], max_length=100, null=True)),
                ('disposition_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('docs', models.FileField(blank=True, null=True, upload_to='employees/leave-docs')),
                ('approval_remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('rule', models.CharField(blank=True, max_length=250, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('datacom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacom.Datacom')),
                ('employees', models.ManyToManyField(blank=True, to='employees.Employee')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Partner')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, eventtools.models.OccurrenceMixin),
        ),
        migrations.CreateModel(
            name='TimeCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punchType', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('is_late', models.BooleanField(default=False)),
                ('is_onLeave', models.BooleanField(default=False)),
                ('clock_in_time', models.DateTimeField(blank=True, null=True, verbose_name='Clock-In DateTime')),
                ('clock_out_time', models.DateTimeField(blank=True, null=True, verbose_name='Clock-In DateTime')),
                ('remark', models.CharField(blank=True, max_length=250, null=True)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.PayCycle')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('attendance_type', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('require_clock_in', models.BooleanField(blank=True, default=False, null=True)),
                ('require_clock_out', models.BooleanField(blank=True, default=False, null=True)),
                ('auto_deduct_meal', models.BooleanField(blank=True, default=False, null=True)),
                ('meal_minutes', models.IntegerField(blank=True, default=0, null=True)),
                ('auto_deduct_break', models.BooleanField(blank=True, default=False, null=True)),
                ('break_minutes', models.IntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('start_clockin_time', models.TimeField(blank=True, null=True)),
                ('stop_clockout_time', models.TimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('datacom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacom.Datacom')),
                ('employees', models.ManyToManyField(blank=True, to='employees.Employee')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='PayCycleRecurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('repeat', eventtools.models.ChoiceTextField(blank=True, choices=[('RRULE:FREQ=DAILY', 'Daily'), ('RRULE:FREQ=WEEKLY', 'Weekly'), ('RRULE:FREQ=MONTHLY', 'Monthly'), ('RRULE:FREQ=YEARLY', 'Yearly')], default='')),
                ('repeat_until', models.DateField(blank=True, null=True)),
                ('recurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.PayCycle')),
            ],
            options={
                'ordering': ('start', 'end'),
                'abstract': False,
            },
            bases=(models.Model, eventtools.models.OccurrenceMixin),
        ),
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('datacom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacom.Datacom')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessOperatingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=15)),
                ('isOpen', models.BooleanField(default=False)),
                ('open', models.CharField(blank=True, max_length=10, null=True)),
                ('close', models.CharField(blank=True, max_length=10, null=True)),
                ('open2', models.CharField(blank=True, max_length=10, null=True)),
                ('close2', models.CharField(blank=True, max_length=10, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('datacom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacom.Datacom')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_company', models.BooleanField(default=False)),
                ('is_location', models.BooleanField(default=False)),
                ('workday_hours', models.IntegerField(blank=True, default=8, null=True)),
                ('name', models.CharField(max_length=250)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('allow_overtime', models.BooleanField(default=False)),
                ('allow_clockin_early', models.BooleanField(default=False)),
                ('allow_clockout_late', models.BooleanField(default=False)),
                ('is_overtime_over_40', models.BooleanField(default=False)),
                ('is_weekend_overtime', models.BooleanField(default=False)),
                ('is_holiday_overtime', models.BooleanField(default=False)),
                ('overtime_hrs_per_day', models.IntegerField(blank=True, default=0, null=True)),
                ('late_clockin_late_minutes', models.IntegerField(blank=True, default=0, null=True)),
                ('early_clockout_minutes', models.IntegerField(blank=True, default=0, null=True)),
                ('late_clockin_absent_minutes', models.IntegerField(blank=True, default=0, null=True)),
                ('early_clockout_absent_minutes', models.IntegerField(blank=True, default=0, null=True)),
                ('no_clockin_is', models.CharField(blank=True, max_length=250, null=True)),
                ('no_clock_out_is', models.CharField(blank=True, max_length=250, null=True)),
                ('notify_no_clockin', models.BooleanField(default=False)),
                ('notify_no_clockout', models.BooleanField(default=False)),
                ('notify_clockin_late', models.BooleanField(default=False)),
                ('notify_clockout_early', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('datacom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacom.Datacom')),
                ('operating_hours', models.ManyToManyField(blank=True, to='attendance.BusinessOperatingHours')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Partner')),
                ('shift', models.ManyToManyField(blank=True, related_name='attendance_shift', to='attendance.Shift')),
            ],
        ),
    ]
