# Generated by Django 2.1.12 on 2020-06-11 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20200609_0318'),
        ('datacom', '0003_auto_20200609_0318'),
        ('companies', '0003_auto_20200609_0318'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOperatingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=15, unique=True)),
                ('isOpen', models.BooleanField(default=False)),
                ('open', models.TimeField(blank=True, null=True)),
                ('close', models.TimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('datacom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacom.Datacom')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Partner')),
            ],
        ),
        migrations.RemoveField(
            model_name='operatinghours',
            name='friday_close',
        ),
        migrations.RemoveField(
            model_name='operatinghours',
            name='friday_open',
        ),
        migrations.RemoveField(
            model_name='operatinghours',
            name='monday_close',
        ),
        migrations.RemoveField(
            model_name='operatinghours',
            name='monday_open',
        ),
        migrations.RemoveField(
            model_name='operatinghours',
            name='saturday_close',
        ),
        migrations.RemoveField(
            model_name='operatinghours',
            name='saturday_open',
        ),
        migrations.RemoveField(
            model_name='operatinghours',
            name='sunday_close',
        ),
        migrations.RemoveField(
            model_name='operatinghours',
            name='sunday_open',
        ),
        migrations.RemoveField(
            model_name='operatinghours',
            name='thursday_close',
        ),
        migrations.RemoveField(
            model_name='operatinghours',
            name='thursday_open',
        ),
        migrations.RemoveField(
            model_name='operatinghours',
            name='tuesday_close',
        ),
        migrations.RemoveField(
            model_name='operatinghours',
            name='tuesday_open',
        ),
        migrations.RemoveField(
            model_name='operatinghours',
            name='wednesday_close',
        ),
        migrations.RemoveField(
            model_name='operatinghours',
            name='wednesday_open',
        ),
    ]
