# Generated by Django 2.1.12 on 2020-06-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20200611_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessoperatinghours',
            name='close',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='businessoperatinghours',
            name='open',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
