# Generated by Django 2.1.12 on 2020-06-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20200612_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessoperatinghours',
            name='close',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='businessoperatinghours',
            name='open',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
