# Generated by Django 2.1.12 on 2020-06-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20200612_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesettings',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='businessoperatinghours',
            name='day_of_week',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='paycycles',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
