# Generated by Django 3.0.7 on 2020-06-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20200612_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessoperatinghours',
            name='close2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='businessoperatinghours',
            name='open2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
