# Generated by Django 3.0.7 on 2020-06-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20200612_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesettings',
            name='operating_hours',
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='operating_hours',
            field=models.ManyToManyField(blank=True, to='attendance.OperatingHours'),
        ),
    ]
