# Generated by Django 3.0.7 on 2020-06-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('attendance', '0008_auto_20200613_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='auto_deduct_break',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='auto_deduct_meal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='require_clock_in',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='require_clock_out',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
