# Generated by Django 3.0.7 on 2020-06-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('attendance', '0009_auto_20200618_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='employees',
            field=models.ManyToManyField(blank=True, to='employees.Employee'),
        ),
    ]
