# Generated by Django 2.1.12 on 2020-06-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20200609_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='billing_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
