# Generated by Django 3.0.7 on 2020-06-26 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_auto_20200609_0318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='billing_contact_list',
            new_name='billing_contacts',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='primary_contact_list',
            new_name='primary_contacts',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='shipping_contact_list',
            new_name='shipping_contacts',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='technical_contact_list',
            new_name='technical_contacts',
        ),
    ]
