# Generated by Django 3.0.7 on 2020-07-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_auto_20200626_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='domain',
        ),
    ]
