# Generated by Django 3.0.7 on 2021-02-12 20:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commons', '0001_initial'),
        ('humanresources', '0001_initial'),
        ('datacom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('global_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('primary_mailing_address', models.CharField(max_length=200)),
                ('primary_mailing_address_2', models.CharField(blank=True, max_length=200, null=True)),
                ('primary_mailing_city', models.CharField(max_length=60)),
                ('primary_mailing_state', models.CharField(max_length=20)),
                ('primary_mailing_zip', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,5}$')])),
                ('primary_mailing_country', models.CharField(max_length=200)),
                ('primary_first_name', models.CharField(max_length=100)),
                ('primary_last_name', models.CharField(max_length=100)),
                ('primary_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('primary_fax', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('primary_email', models.CharField(max_length=200)),
                ('shipping_address', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_address_2', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=60, null=True)),
                ('shipping_state', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_zip', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,5}$')])),
                ('shipping_country', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('shipping_fax', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('shipping_email', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_address_2', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=60, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_zip', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,5}$')])),
                ('billing_country', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('billing_fax', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('billing_email', models.CharField(blank=True, max_length=200, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,9}$')])),
                ('resale_id', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,20}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_datacom', models.BooleanField(blank=True, default=False, null=True)),
                ('is_partner', models.BooleanField(blank=True, default=False, null=True)),
                ('is_merchant', models.BooleanField(blank=True, default=False, null=True)),
                ('is_vendor', models.BooleanField(blank=True, default=False, null=True)),
                ('is_warehouse', models.BooleanField(blank=True, default=False, null=True)),
                ('is_salesoffice', models.BooleanField(blank=True, default=False, null=True)),
                ('board_date', models.DateField(blank=True, null=True)),
                ('closure_date', models.DateField(blank=True, null=True)),
                ('closure_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('dba_name', models.CharField(max_length=200, unique=True)),
                ('legal_name', models.CharField(max_length=200, unique=True)),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('account_number', models.CharField(blank=True, max_length=16, null=True)),
                ('merchant_id', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,9}$')])),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/logo')),
                ('barcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commons.CommonBarcode')),
                ('billing_contacts', models.ManyToManyField(blank=True, related_name='partner_billing_contacts', to=settings.AUTH_USER_MODEL)),
                ('company_docs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humanresources.CompanyDocuments')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='partner_creator', to=settings.AUTH_USER_MODEL)),
                ('datacom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datacom.Datacom')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commons.Industry')),
                ('primary_contacts', models.ManyToManyField(blank=True, related_name='partner_primary_contacts', to=settings.AUTH_USER_MODEL)),
                ('shipping_contacts', models.ManyToManyField(blank=True, related_name='partner_shipping_contacts', to=settings.AUTH_USER_MODEL)),
                ('technical_contacts', models.ManyToManyField(blank=True, related_name='partner_technical_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
