# Generated by Django 3.0.7 on 2021-02-12 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
        ('partners', '0001_initial'),
        ('datacom', '0001_initial'),
        ('commons2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='date paid')),
                ('invoice_number', models.CharField(blank=True, max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('terms', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('created_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.Customer')),
                ('datacom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacom.Datacom')),
                ('inventory', models.ManyToManyField(blank=True, to='inventory.Inventory')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Partner')),
                ('shipping', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commons2.Shipping')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('date_paid', models.DateTimeField(blank=True, null=True, verbose_name='date paid')),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_items', models.IntegerField(blank=True, null=True)),
                ('total_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('terms', models.CharField(blank=True, max_length=255, null=True)),
                ('form_of_pmt1', models.CharField(choices=[('ACH', 'ACH'), ('Cash', 'Cash'), ('Check', 'Check'), ('Credit', 'Credit'), ('Debit', 'Debit'), ('On-Account', 'On-Account')], default='Credit', max_length=100)),
                ('form_of_pmt1_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('form_of_pmt2', models.CharField(choices=[('ACH', 'ACH'), ('Cash', 'Cash'), ('Check', 'Check'), ('Credit', 'Credit'), ('Debit', 'Debit'), ('On-Account', 'On-Account')], default='Credit', max_length=100)),
                ('form_of_pmt2_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('form_of_pmt3', models.CharField(choices=[('ACH', 'ACH'), ('Cash', 'Cash'), ('Check', 'Check'), ('Credit', 'Credit'), ('Debit', 'Debit'), ('On-Account', 'On-Account')], default='Credit', max_length=100)),
                ('form_of_pmt3_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.Customer')),
                ('datacom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacom.Datacom')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Partner')),
            ],
        ),
    ]
