# Generated by Django 3.0.7 on 2020-06-20 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacom', '0004_auto_20200612_1714'),
        ('companies', '0003_auto_20200609_0318'),
        ('partners', '0003_auto_20200609_0318'),
        ('customers', '0001_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='total',
            new_name='total_amt',
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('date_paid', models.DateTimeField(blank=True, null=True, verbose_name='date paid')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_items', models.IntegerField(blank=True, null=True)),
                ('total_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('terms', models.CharField(blank=True, max_length=255, null=True)),
                ('form_of_pmt1', models.CharField(choices=[('ACH', 'ACH'), ('Cash', 'Cash'), ('Check', 'Check'), ('Credit', 'Credit'), ('Debit', 'Debit'), ('On-Account', 'On-Account')], default='Credit', max_length=100)),
                ('form_of_pmt1_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('form_of_pmt2', models.CharField(choices=[('ACH', 'ACH'), ('Cash', 'Cash'), ('Check', 'Check'), ('Credit', 'Credit'), ('Debit', 'Debit'), ('On-Account', 'On-Account')], default='Credit', max_length=100)),
                ('form_of_pmt2_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('form_of_pmt3', models.CharField(choices=[('ACH', 'ACH'), ('Cash', 'Cash'), ('Check', 'Check'), ('Credit', 'Credit'), ('Debit', 'Debit'), ('On-Account', 'On-Account')], default='Credit', max_length=100)),
                ('form_of_pmt3_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.Customer')),
                ('datacom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacom.Datacom')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Partner')),
            ],
        ),
    ]
