# Generated by Django 3.0.7 on 2020-06-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20200620_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date paid'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='reference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
