# Generated by Django 3.0.7 on 2020-06-25 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humanresources', '0003_auto_20200625_0305'),
        ('companies', '0003_auto_20200609_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_docs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humanresources.CompanyDocuments'),
        ),
    ]
