# Generated by Django 2.1.12 on 2020-06-05 19:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('datacom', '0001_initial'),
        ('companies', '0001_initial'),
        ('employees', '0001_initial'),
        ('salesoffices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(blank=True, max_length=200, null=True)),
                ('warehouse_number', models.CharField(blank=True, max_length=20, null=True)),
                ('global_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='warehouses/profile')),
                ('description', models.TextField(blank=True, null=True)),
                ('primary_mailing_address', models.CharField(blank=True, max_length=200, null=True)),
                ('primary_mailing_city', models.CharField(blank=True, max_length=60, null=True)),
                ('primary_mailing_state', models.CharField(blank=True, max_length=20, null=True)),
                ('primary_mailing_zip', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,5}$')])),
                ('primary_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('primary_fax', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('primary_email', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=60, null=True)),
                ('shipping_state', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_zip', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,5}$')])),
                ('shipping_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('shipping_fax', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('shipping_email', models.CharField(blank=True, max_length=200, null=True)),
                ('closure_date', models.DateField(blank=True, null=True)),
                ('closure_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('barcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datacom.CommonBarcode')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('datacom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacom.Datacom')),
                ('employees', models.ManyToManyField(blank=True, related_name='warehouse_employees', to='employees.Employee')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Partner')),
                ('primary_contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.Employee')),
                ('sales_offices', models.ManyToManyField(blank=True, related_name='warehouse_salesoffice', to='salesoffices.SalesOffice')),
                ('shipping_contacts', models.ManyToManyField(blank=True, related_name='shipping_contacts', to='employees.Employee')),
            ],
        ),
    ]
