# Generated by Django 3.0.7 on 2020-06-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='primary_mailing_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='shipping_mailing_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
