# Generated by Django 3.0.7 on 2020-06-26 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouses', '0002_auto_20200619_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='primary_contact',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='billing_contacts',
            field=models.ManyToManyField(blank=True, related_name='warehouse_billing_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='primary_contacts',
            field=models.ManyToManyField(blank=True, related_name='warehouse_primary_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='technical_contacts',
            field=models.ManyToManyField(blank=True, related_name='warehouse_technical_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='shipping_contacts',
            field=models.ManyToManyField(blank=True, related_name='warehouse_shipping_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
