# Generated by Django 3.0.7 on 2020-06-26 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0003_auto_20200626_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['date_added', 'id', 'warehouse_name']},
        ),
    ]
