# Generated by Django 3.0.7 on 2020-08-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0005_auto_20200626_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='primary_mailing_address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
