# Generated by Django 3.0.7 on 2020-07-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_commonbarcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonbarcode',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
