# Generated by Django 3.0.7 on 2020-08-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0003_auto_20200721_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonbarcode',
            name='image',
        ),
        migrations.RemoveField(
            model_name='commonbarcode',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='commonbarcode',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='commonbarcode',
            name='title',
        ),
    ]
