# Generated by Django 3.0.7 on 2020-08-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0004_auto_20200821_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonbarcode',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
