# Generated by Django 2.1.12 on 2020-06-05 19:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datacom', '0001_initial'),
        ('companies', '0001_initial'),
        ('vendors', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,16}$')])),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('salary_type', models.CharField(blank=True, max_length=50, null=True)),
                ('pay_cycle', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_type', models.CharField(blank=True, max_length=20, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('is_business', models.BooleanField(blank=True, default=False, null=True)),
                ('is_sales_rep', models.BooleanField(blank=True, default=False, null=True)),
                ('is_warehouse_ee', models.BooleanField(blank=True, default=False, null=True)),
                ('is_exempt', models.BooleanField(blank=True, default=False, null=True)),
                ('is_manager', models.BooleanField(blank=True, default=False, null=True)),
                ('reporting_manager', models.CharField(blank=True, max_length=250, null=True)),
                ('hire_date', models.DateTimeField(blank=True, null=True)),
                ('termination_date', models.DateTimeField(blank=True, null=True)),
                ('termination_reason', models.TextField(blank=True, null=True)),
                ('ssn', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,9}$')])),
                ('dob', models.DateField(blank=True, null=True)),
                ('medical_ins', models.BooleanField(blank=True, default=False, null=True)),
                ('accident_ins', models.BooleanField(blank=True, default=False, null=True)),
                ('dental_ins', models.BooleanField(blank=True, default=False, null=True)),
                ('vision_ins', models.BooleanField(blank=True, default=False, null=True)),
                ('retirement', models.BooleanField(blank=True, default=False, null=True)),
                ('org_name', models.CharField(blank=True, max_length=100, null=True)),
                ('handbook', models.FileField(blank=True, null=True, upload_to='employee/')),
                ('signed_handbook', models.BooleanField(blank=True, default=False, null=True)),
                ('policies_procedures', models.FileField(blank=True, null=True, upload_to='employee/')),
                ('signed_pp', models.BooleanField(blank=True, default=False, null=True)),
                ('code_conduct', models.FileField(blank=True, null=True, upload_to='employee/')),
                ('signed_code', models.BooleanField(blank=True, default=False, null=True)),
                ('employment_agmt', models.FileField(blank=True, null=True, upload_to='employee/')),
                ('signed_ee_agmt', models.BooleanField(blank=True, default=False, null=True)),
                ('compensation_plan', models.FileField(blank=True, null=True, upload_to='employee/')),
                ('signed_comp_plan', models.BooleanField(blank=True, default=False, null=True)),
                ('personal_days_rem', models.IntegerField(blank=True, null=True)),
                ('vacation_days_rem', models.IntegerField(blank=True, null=True)),
                ('sick_days_rem', models.IntegerField(blank=True, null=True)),
                ('pto_days_rem', models.IntegerField(blank=True, null=True)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='employees/profile/')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('datacom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacom.Datacom')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commons2.Department')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Partner')),
            ],
            options={
                'ordering': ['user__last_name', 'hire_date'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('datacom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacom.Datacom')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Partner')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.Position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor'),
        ),
    ]
