# Generated by Django 3.0.7 on 2021-02-12 20:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commons', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('humanresources', '0001_initial'),
        ('vendors', '0001_initial'),
        ('commons2', '0001_initial'),
        ('companies', '0001_initial'),
        ('datacom', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('datacom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacom.Datacom')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_module_manager', models.BooleanField(blank=True, default=False, null=True)),
                ('employee_number', models.CharField(blank=True, max_length=16, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('salary_type', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_type', models.CharField(blank=True, max_length=20, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('is_employee', models.BooleanField(blank=True, default=True, null=True)),
                ('is_business', models.BooleanField(blank=True, default=False, null=True)),
                ('is_sales_office_ee', models.BooleanField(blank=True, default=False, null=True)),
                ('is_sales_rep', models.BooleanField(blank=True, default=False, null=True)),
                ('is_warehouse_ee', models.BooleanField(blank=True, default=False, null=True)),
                ('is_exempt', models.BooleanField(blank=True, default=False, null=True)),
                ('is_manager', models.BooleanField(blank=True, default=False, null=True)),
                ('reporting_manager', models.CharField(blank=True, max_length=250, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('termination_reason', models.TextField(blank=True, null=True)),
                ('ssn', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,9}$')])),
                ('dob', models.DateField(blank=True, null=True)),
                ('org_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='employees/profile/')),
                ('barcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commons.CommonBarcode')),
                ('benefits', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humanresources.Benefits')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('datacom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacom.Datacom')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commons2.Department')),
                ('employee_docs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humanresources.EmployeeDocuments')),
                ('modules_managed', models.ManyToManyField(blank=True, to='contenttypes.ContentType')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Partner')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.Position')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor')),
            ],
            options={
                'ordering': ['user__last_name', 'hire_date'],
            },
        ),
    ]
