# Generated by Django 3.0.7 on 2020-06-25 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humanresources', '0002_auto_20200625_0056'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='accident_ins',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='code_conduct',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='compensation_plan',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dental_ins',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employment_agmt',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='handbook',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='medical_ins',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='personal_days_rem',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='policies_procedures',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pto_days_rem',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='retirement',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='sick_days_rem',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='signed_code',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='signed_comp_plan',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='signed_ee_agmt',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='signed_handbook',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='signed_pp',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='vacation_days_rem',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='vision_ins',
        ),
        migrations.AddField(
            model_name='employee',
            name='benefits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humanresources.Benefits'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_docs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humanresources.EmployeeDocuments'),
        ),
    ]
