# Generated by Django 3.0.7 on 2020-06-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('employees', '0002_auto_20200625_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='pay_cycle',
        ),
        migrations.AddField(
            model_name='employee',
            name='modules_managed',
            field=models.ManyToManyField(blank=True, to='contenttypes.ContentType'),
        ),
    ]
