# Generated by Django 3.0.7 on 2020-06-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20200625_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_module_manager',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
