# Generated by Django 3.0.7 on 2020-06-26 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20200625_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='modules_managed',
        ),
    ]
