# Generated by Django 3.0.7 on 2020-06-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('employees', '0007_remove_employee_modules_managed'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='modules_managed',
            field=models.ManyToManyField(blank=True, to='contenttypes.ContentType'),
        ),
    ]
