# Generated by Django 3.0.7 on 2020-07-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_modules_managed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
