# Generated by Django 3.0.7 on 2021-02-12 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='openAndCloseTill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_open', models.BooleanField(blank=True, default=False, null=True)),
                ('open_pennies', models.IntegerField(blank=True, default=0, null=True)),
                ('open_nickels', models.IntegerField(blank=True, default=0, null=True)),
                ('open_dimes', models.IntegerField(blank=True, default=0, null=True)),
                ('open_quarters', models.IntegerField(blank=True, default=0, null=True)),
                ('open_halfDollars', models.IntegerField(blank=True, default=0, null=True)),
                ('open_dollarCoins', models.IntegerField(blank=True, default=0, null=True)),
                ('open_ones', models.IntegerField(blank=True, default=0, null=True)),
                ('open_fives', models.IntegerField(blank=True, default=0, null=True)),
                ('open_tens', models.IntegerField(blank=True, default=0, null=True)),
                ('open_twenties', models.IntegerField(blank=True, default=0, null=True)),
                ('open_fiftys', models.IntegerField(blank=True, default=0, null=True)),
                ('open_hundreds', models.IntegerField(blank=True, default=0, null=True)),
                ('close_pennies', models.IntegerField(blank=True, default=0, null=True)),
                ('close_nickels', models.IntegerField(blank=True, default=0, null=True)),
                ('close_dimes', models.IntegerField(blank=True, default=0, null=True)),
                ('close_quarters', models.IntegerField(blank=True, default=0, null=True)),
                ('close_halfDollars', models.IntegerField(blank=True, default=0, null=True)),
                ('close_dollarCoins', models.IntegerField(blank=True, default=0, null=True)),
                ('close_ones', models.IntegerField(blank=True, default=0, null=True)),
                ('close_fives', models.IntegerField(blank=True, default=0, null=True)),
                ('close_tens', models.IntegerField(blank=True, default=0, null=True)),
                ('close_twenties', models.IntegerField(blank=True, default=0, null=True)),
                ('close_fiftys', models.IntegerField(blank=True, default=0, null=True)),
                ('close_hundreds', models.IntegerField(blank=True, default=0, null=True)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.Employee')),
            ],
        ),
    ]
