# Generated by Django 3.0.7 on 2020-06-13 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_auto_20200609_0318'),
        ('datacom', '0004_auto_20200612_1714'),
        ('partners', '0003_auto_20200609_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('state_agency_name', models.CharField(max_length=250)),
                ('state_agency_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('local_tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('filing_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='Monthly', max_length=100)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('datacom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacom.Datacom')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Partner')),
            ],
        ),
    ]
