# Generated by Django 3.0.7 on 2020-06-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestax',
            name='enable_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
