# Generated by Django 3.0.7 on 2020-06-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesoffices', '0003_auto_20200609_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesoffice',
            name='billing_mailing_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='salesoffice',
            name='shipping_mailing_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salesoffice',
            name='primary_mailing_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
