# Generated by Django 3.0.7 on 2020-06-26 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salesoffices', '0005_auto_20200626_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesoffice',
            name='primary_contact',
        ),
        migrations.AddField(
            model_name='salesoffice',
            name='primary_contacts',
            field=models.ManyToManyField(blank=True, related_name='salesoffice_primary_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesoffice',
            name='shipping_contacts',
            field=models.ManyToManyField(blank=True, related_name='salesoffice_shipping_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesoffice',
            name='technical_contacts',
            field=models.ManyToManyField(blank=True, related_name='salesoffice_technical_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesoffice',
            name='billing_contacts',
            field=models.ManyToManyField(blank=True, related_name='salesoffice_billing_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
