# Generated by Django 3.0.7 on 2020-08-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesoffices', '0011_auto_20200721_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesoffice',
            name='primary_mailing_address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
